version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 779846785052.dkr.ecr.<your-region>.amazonaws.com
      - REPOSITORY_URI=779846785052.dkr.ecr.us-east-1.amazonaws.com/jani-ecr-repo
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
